version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./engine:/engine
