name: Build on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        bootstrap-vcpkg.bat

    - name: Install dependencies with vcpkg
      run: |
        cd ..
        vcpkg/vcpkg install --triplet x64-windows --overlay-triplets

    - name: Configure with CMake
      run: cmake .

    - name: Build with CMake
      run: cmake --build .
