name: Mirror Push workflow

on: [ push ]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-CPP-500-PAR-5-2-rtype-laetitia.bousch.git"

jobs:
  push_to_mirror:
    name: Push New Project Version
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == "push"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
